package com.bachelor.toolbox.migration;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContextInitializer;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.test.context.ContextConfiguration;

@SpringBootTest(
    properties = {
      "spring.datasource.url=" + LegacyProjectSchemaMigrationIntegrationTests.URL,
      "spring.datasource.username=sa",
      "spring.datasource.password=",
      "spring.jpa.hibernate.ddl-auto=update",
      "spring.task.scheduling.enabled=false",
      "toolbox.ai.agent.runtime-enabled=false",
      "toolbox.auth.admin-password=test-admin-password-7bbbe095d8724fcb",
      "toolbox.auth.jwt-secret=test-jwt-secret-cdc24d415ad843aa9ef313028ae9be30",
      "toolbox.traffic.mitm-ca-password=test-mitm-ca-password-1d6ad9b95b76490e",
      "toolbox.traffic.mitm-enabled=false",
      "toolbox.vulnerability-catalog.nuclei.import-on-startup=false",
      "toolbox.vulnerability-catalog.cisa-kev-enabled=false"
    })
@ContextConfiguration(
    initializers = LegacyProjectSchemaMigrationIntegrationTests.LegacySchemaInitializer.class)
class LegacyProjectSchemaMigrationIntegrationTests {
  static final String URL =
      "jdbc:h2:mem:legacy-project-migration;MODE=PostgreSQL;DB_CLOSE_DELAY=-1";

  @Autowired DataSource dataSource;
  @Autowired LegacyProjectSchemaMigration migration;

  @Test
  void migratesOldTaskAndScheduleSchemaBeforeHibernateUpdate() throws Exception {
    JdbcTemplate jdbc = new JdbcTemplate(dataSource);

    assertEquals(1, jdbc.queryForObject("SELECT COUNT(*) FROM security_tasks", Integer.class));
    assertEquals(
        10L, jdbc.queryForObject("SELECT project_id FROM security_tasks WHERE id=100", Long.class));
    assertEquals(1, jdbc.queryForObject("SELECT COUNT(*) FROM findings", Integer.class));
    assertEquals(1000L, jdbc.queryForObject("SELECT id FROM findings", Long.class));
    assertEquals(1, jdbc.queryForObject("SELECT COUNT(*) FROM scan_schedules", Integer.class));
    assertEquals(
        10L, jdbc.queryForObject("SELECT project_id FROM scan_schedules WHERE id=400", Long.class));
    assertNull(
        jdbc.queryForObject("SELECT last_task_id FROM scan_schedules WHERE id=400", Long.class));
    assertFalse(isNullable(dataSource, "SECURITY_TASKS", "PROJECT_ID"));
    assertFalse(isNullable(dataSource, "SCAN_SCHEDULES", "PROJECT_ID"));

    // The migration must remain safe after a partially migrated or already current startup.
    migration.migrate();
    assertEquals(1, jdbc.queryForObject("SELECT COUNT(*) FROM security_tasks", Integer.class));
    assertEquals(1, jdbc.queryForObject("SELECT COUNT(*) FROM scan_schedules", Integer.class));
  }

  @Test
  void repairsProjectlessTaskTableWithoutDeletingUnrelatedTables() throws Exception {
    String legacyUrl = "jdbc:h2:mem:legacy-projectless-tasks;MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
    DriverManagerDataSource legacyDataSource = new DriverManagerDataSource(legacyUrl, "sa", "");
    JdbcTemplate jdbc = new JdbcTemplate(legacyDataSource);
    jdbc.execute("DROP ALL OBJECTS");
    jdbc.execute(
        """
        CREATE TABLE security_tasks (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          target_id BIGINT NOT NULL,
          tool_code VARCHAR(50) NOT NULL,
          status VARCHAR(30) NOT NULL,
          progress INTEGER NOT NULL,
          request_json CLOB,
          result_json CLOB,
          execution_log CLOB,
          error_message VARCHAR(2000),
          created_at TIMESTAMP WITH TIME ZONE NOT NULL,
          started_at TIMESTAMP WITH TIME ZONE,
          finished_at TIMESTAMP WITH TIME ZONE,
          rule_code VARCHAR(64),
          vulnerability_code VARCHAR(64)
        )
        """);
    jdbc.execute(
        """
        CREATE TABLE local_preferences (
          id BIGINT PRIMARY KEY,
          preference_value VARCHAR(100) NOT NULL
        )
        """);
    jdbc.update(
        """
        INSERT INTO security_tasks
        (id,target_id,tool_code,status,progress,created_at)
        VALUES (1,99,'http_headers','SUCCESS',100,CURRENT_TIMESTAMP)
        """);
    jdbc.update("INSERT INTO local_preferences(id,preference_value) VALUES (1,'keep-me')");

    LegacyProjectSchemaMigration legacyMigration =
        new LegacyProjectSchemaMigration(legacyDataSource);
    legacyMigration.migrate();

    assertEquals(0, jdbc.queryForObject("SELECT COUNT(*) FROM security_tasks", Integer.class));
    assertFalse(isNullable(legacyDataSource, "SECURITY_TASKS", "PROJECT_ID"));
    assertEquals(
        "keep-me",
        jdbc.queryForObject(
            "SELECT preference_value FROM local_preferences WHERE id=1", String.class));

    // A second startup must be a no-op and must still preserve unrelated data.
    legacyMigration.migrate();
    assertEquals(
        "keep-me",
        jdbc.queryForObject(
            "SELECT preference_value FROM local_preferences WHERE id=1", String.class));
  }

  @Test
  void repairsLegacyAiGeneratedIdsWithoutLosingRows() throws Exception {
    String legacyUrl = "jdbc:h2:mem:legacy-ai-generated-ids;MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
    DriverManagerDataSource legacyDataSource = new DriverManagerDataSource(legacyUrl, "sa", "");
    JdbcTemplate jdbc = new JdbcTemplate(legacyDataSource);
    jdbc.execute("DROP ALL OBJECTS");
    jdbc.execute(
        """
        CREATE TABLE agent_workflow_spec (
          id BIGINT NOT NULL PRIMARY KEY,
          workflow_id VARCHAR(64) NOT NULL,
          scope_id BIGINT NOT NULL,
          revision BIGINT NOT NULL,
          spec_digest VARCHAR(71) NOT NULL,
          spec_json CLOB NOT NULL,
          updated_by VARCHAR(100) NOT NULL,
          updated_at TIMESTAMP WITH TIME ZONE NOT NULL
        )
        """);
    jdbc.update(
        """
        INSERT INTO agent_workflow_spec
        (id,workflow_id,scope_id,revision,spec_digest,spec_json,updated_by,updated_at)
        VALUES (7,'legacy-workflow',10,1,'sha256:legacy','{}','admin',CURRENT_TIMESTAMP)
        """);

    LegacyProjectSchemaMigration legacyMigration =
        new LegacyProjectSchemaMigration(legacyDataSource);
    legacyMigration.migrate();

    assertTrue(isAutoIncrement(legacyDataSource, "AGENT_WORKFLOW_SPEC", "ID"));
    jdbc.update(
        """
        INSERT INTO agent_workflow_spec
        (workflow_id,scope_id,revision,spec_digest,spec_json,updated_by,updated_at)
        VALUES ('legacy-workflow',10,2,'sha256:next','{}','admin',CURRENT_TIMESTAMP)
        """);
    assertEquals(
        8L,
        jdbc.queryForObject(
            "SELECT id FROM agent_workflow_spec WHERE revision=2", Long.class));

    legacyMigration.migrate();
    assertEquals(2, jdbc.queryForObject("SELECT COUNT(*) FROM agent_workflow_spec", Integer.class));
  }

  private boolean isNullable(DataSource source, String table, String column) throws Exception {
    try (Connection connection = source.getConnection()) {
      DatabaseMetaData metadata = connection.getMetaData();
      try (ResultSet columns = metadata.getColumns(null, null, table, column)) {
        columns.next();
        return columns.getInt("NULLABLE") != DatabaseMetaData.columnNoNulls;
      }
    }
  }

  private boolean isAutoIncrement(DataSource source, String table, String column) throws Exception {
    try (Connection connection = source.getConnection()) {
      DatabaseMetaData metadata = connection.getMetaData();
      try (ResultSet columns = metadata.getColumns(null, null, table, column)) {
        columns.next();
        return "YES".equalsIgnoreCase(columns.getString("IS_AUTOINCREMENT"));
      }
    }
  }

  static final class LegacySchemaInitializer
      implements ApplicationContextInitializer<ConfigurableApplicationContext> {
    @Override
    public void initialize(ConfigurableApplicationContext applicationContext) {
      try (Connection connection = DriverManager.getConnection(URL, "sa", "");
          Statement sql = connection.createStatement()) {
        sql.execute("DROP ALL OBJECTS");
        sql.execute(
            """
            CREATE TABLE assessment_projects (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name VARCHAR(150) NOT NULL,
              description VARCHAR(2000),
              authorization_statement VARCHAR(4000) NOT NULL,
              authorization_valid_from TIMESTAMP WITH TIME ZONE NOT NULL,
              authorization_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
              status VARCHAR(30) NOT NULL,
              owner VARCHAR(100) NOT NULL,
              created_at TIMESTAMP WITH TIME ZONE NOT NULL,
              updated_at TIMESTAMP WITH TIME ZONE
            )
            """);
        sql.execute(
            """
            CREATE TABLE assessment_project_targets (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              project_id BIGINT NOT NULL,
              target_id BIGINT NOT NULL,
              added_at TIMESTAMP WITH TIME ZONE NOT NULL,
              CONSTRAINT uq_legacy_project_target UNIQUE(project_id, target_id)
            )
            """);
        sql.execute(
            """
            CREATE TABLE security_tasks (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              target_id BIGINT NOT NULL,
              tool_code VARCHAR(50) NOT NULL,
              status VARCHAR(30) NOT NULL,
              progress INTEGER NOT NULL,
              created_at TIMESTAMP WITH TIME ZONE NOT NULL
            )
            """);
        sql.execute(
            """
            CREATE TABLE findings (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              task_id BIGINT NOT NULL,
              target_id BIGINT NOT NULL,
              title VARCHAR(300) NOT NULL,
              severity VARCHAR(20) NOT NULL,
              source_tool VARCHAR(50) NOT NULL,
              rule_code VARCHAR(64),
              vulnerability_code VARCHAR(64),
              status VARCHAR(30) NOT NULL,
              description CLOB,
              evidence CLOB,
              remediation CLOB,
              created_at TIMESTAMP WITH TIME ZONE NOT NULL
            )
            """);
        sql.execute(
            """
            CREATE TABLE scan_schedules (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              target_id BIGINT NOT NULL,
              tool_code VARCHAR(50) NOT NULL,
              parameters_json CLOB,
              cron_expression VARCHAR(120),
              interval_seconds BIGINT,
              enabled BOOLEAN NOT NULL,
              next_run_at TIMESTAMP WITH TIME ZONE,
              last_run_at TIMESTAMP WITH TIME ZONE,
              last_task_id BIGINT,
              created_at TIMESTAMP WITH TIME ZONE NOT NULL
            )
            """);
        sql.execute(
            """
            INSERT INTO assessment_projects
            (id,name,authorization_statement,authorization_valid_from,
             authorization_expires_at,status,owner,created_at)
            VALUES
            (10,'Unique project','authorized',CURRENT_TIMESTAMP - INTERVAL '1' DAY,
             CURRENT_TIMESTAMP + INTERVAL '1' DAY,'ACTIVE','admin',CURRENT_TIMESTAMP),
            (11,'Second project','authorized',CURRENT_TIMESTAMP - INTERVAL '1' DAY,
             CURRENT_TIMESTAMP + INTERVAL '1' DAY,'ACTIVE','admin',CURRENT_TIMESTAMP)
            """);
        sql.execute(
            """
            INSERT INTO assessment_project_targets(id,project_id,target_id,added_at) VALUES
            (1,10,101,CURRENT_TIMESTAMP),
            (2,10,102,CURRENT_TIMESTAMP),
            (3,11,102,CURRENT_TIMESTAMP)
            """);
        sql.execute(
            """
            INSERT INTO security_tasks(id,target_id,tool_code,status,progress,created_at) VALUES
            (100,101,'http_headers','SUCCESS',100,CURRENT_TIMESTAMP),
            (200,102,'tcp_ports','SUCCESS',100,CURRENT_TIMESTAMP),
            (300,103,'tls_config','FAILED',100,CURRENT_TIMESTAMP)
            """);
        sql.execute(
            """
INSERT INTO findings(id,task_id,target_id,title,severity,source_tool,status,created_at) VALUES
(1000,100,101,'retained finding','LOW','http_headers','OPEN',CURRENT_TIMESTAMP),
(2000,200,102,'ambiguous finding','LOW','tcp_ports','OPEN',CURRENT_TIMESTAMP),
(3000,300,103,'orphan finding','LOW','tls_config','OPEN',CURRENT_TIMESTAMP)
""");
        sql.execute(
            """
            INSERT INTO scan_schedules
            (id,target_id,tool_code,enabled,interval_seconds,last_task_id,created_at) VALUES
            (400,101,'http_headers',FALSE,3600,200,CURRENT_TIMESTAMP),
            (500,103,'tls_config',FALSE,3600,300,CURRENT_TIMESTAMP)
            """);
      } catch (Exception ex) {
        throw new IllegalStateException("Unable to initialize legacy H2 schema", ex);
      }
    }
  }
}
